"""add_marcas

Revision ID: 93d996331edd
Revises: p6q7r8s9t0u1
Create Date: 2026-04-23 16:11:20.084077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d996331edd'
down_revision: Union[str, Sequence[str], None] = 'p6q7r8s9t0u1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.execute("""
        INSERT INTO marcas (nombre, activa) VALUES
        ('Shell', true), ('Mobil', true), ('Total', true), ('Lubrax', true), ('Otros', true)
    """)
    op.alter_column('cotizacion_lineas', 'descuento',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint('facturas_banco_receptor_id_fkey', 'facturas', type_='foreignkey')
    op.create_foreign_key(None, 'facturas', 'banco_receptores', ['banco_receptor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.create_foreign_key('facturas_banco_receptor_id_fkey', 'facturas', 'banco_receptores', ['banco_receptor_id'], ['id'])
    op.alter_column('cotizacion_lineas', 'descuento',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_table('marcas')
    # ### end Alembic commands ###
