"""add_lotes_costo_producto_documentos

Revision ID: a829239d4f22
Revises: v1w2x3y4z5a6
Create Date: 2026-04-23 16:28:44.780974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a829239d4f22'
down_revision: Union[str, Sequence[str], None] = 'v1w2x3y4z5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('subido_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes_costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('oc_linea_id', sa.Integer(), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_inicial', sa.Integer(), nullable=False),
    sa.Column('cantidad_restante', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['oc_linea_id'], ['orden_compra_lineas.id'], ondelete='SET NULL', use_alter=True, name='fk_lotes_costo_oc_linea_id'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_costo_created_at'), 'lotes_costo', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lotes_costo_oc_linea_id', 'lotes_costo', type_='foreignkey')
    op.drop_index(op.f('ix_lotes_costo_created_at'), table_name='lotes_costo')
    op.drop_table('lotes_costo')
    op.drop_table('producto_documentos')
    # ### end Alembic commands ###
