"""add_nc_nd_and_factura_dte_estado

Revision ID: e43dce1d2bd5
Revises: a060211ee1c6
Create Date: 2026-04-21 15:02:28.499561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43dce1d2bd5'
down_revision: Union[str, Sequence[str], None] = 'a060211ee1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('razon', sa.String(length=500), nullable=False),
    sa.Column('monto_neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dte_estado', sa.String(length=20), server_default=sa.text("'no_emitida'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_credito_numero'), 'notas_credito', ['numero'], unique=True)
    op.create_table('notas_debito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('razon', sa.String(length=500), nullable=False),
    sa.Column('monto_neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dte_estado', sa.String(length=20), server_default=sa.text("'no_emitida'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_debito_numero'), 'notas_debito', ['numero'], unique=True)
    op.create_table('nota_credito_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_credito_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nota_credito_id'], ['notas_credito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_debito_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_debito_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nota_debito_id'], ['notas_debito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orden_compra_lineas')
    op.drop_index(op.f('ix_ordenes_compra_numero'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_table('dashboard_layouts')
    op.alter_column('aprobaciones_credito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('aprobaciones_credito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('aprobaciones_margen', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('aprobaciones_margen', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('clientes_rut_key'), 'clientes', type_='unique')
    op.drop_constraint(op.f('cotizaciones_numero_key'), 'cotizaciones', type_='unique')
    op.drop_constraint(op.f('empresas_rut_key'), 'empresas', type_='unique')
    op.create_index(op.f('ix_empresas_rut'), 'empresas', ['rut'], unique=True)
    op.add_column('facturas', sa.Column('dte_estado', sa.String(length=20), server_default=sa.text("'no_emitida'"), nullable=False))
    op.drop_constraint(op.f('facturas_cliente_id_fkey'), 'facturas', type_='foreignkey')
    op.create_foreign_key(None, 'facturas', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_movimientos_inventario_created_at'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_producto_id'), table_name='movimientos_inventario')
    op.drop_constraint(op.f('proveedores_rut_key'), 'proveedores', type_='unique')
    # ### end Alembic commands ###

    # SystemConfig seeds
    op.execute("INSERT INTO system_config (key, value) VALUES ('nc_last_id', '0') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('nd_last_id', '0') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('rut_emisor', '') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('razon_social_emisor', '') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('giro_emisor', '') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('direccion_emisor', '') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('ciudad_emisor', 'Santiago') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO system_config (key, value) VALUES ('comuna_emisor', '') ON CONFLICT DO NOTHING")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('proveedores_rut_key'), 'proveedores', ['rut'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_movimientos_inventario_producto_id'), 'movimientos_inventario', ['producto_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_created_at'), 'movimientos_inventario', ['created_at'], unique=False)
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.create_foreign_key(op.f('facturas_cliente_id_fkey'), 'facturas', 'clientes', ['cliente_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('facturas', 'dte_estado')
    op.drop_index(op.f('ix_empresas_rut'), table_name='empresas')
    op.create_unique_constraint(op.f('empresas_rut_key'), 'empresas', ['rut'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('cotizaciones_numero_key'), 'cotizaciones', ['numero'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clientes_rut_key'), 'clientes', ['rut'], postgresql_nulls_not_distinct=False)
    op.alter_column('aprobaciones_margen', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('aprobaciones_margen', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('aprobaciones_credito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('aprobaciones_credito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('orden_compra_lineas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orden_compra_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_recibida', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_neto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_neto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('iva', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['ordenes_compra.id'], name=op.f('orden_compra_lineas_orden_compra_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('orden_compra_lineas_producto_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('orden_compra_lineas_pkey'))
    )
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('slot', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text("'Principal'::character varying"), autoincrement=False, nullable=False),
    sa.Column('layout_json', sa.TEXT(), server_default=sa.text("'''{}'''::text"), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('dashboard_layouts_new_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_layouts_new_pkey')),
    sa.UniqueConstraint('role', 'slot', name=op.f('uq_dashboard_role_slot'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ordenes_compra',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_entrega_esperada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('nota', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_neto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_iva', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('ordenes_compra_proveedor_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('ordenes_compra_pkey'))
    )
    op.create_index(op.f('ix_ordenes_compra_numero'), 'ordenes_compra', ['numero'], unique=True)
    op.drop_table('nota_debito_lineas')
    op.drop_table('nota_credito_lineas')
    op.drop_index(op.f('ix_notas_debito_numero'), table_name='notas_debito')
    op.drop_table('notas_debito')
    op.drop_index(op.f('ix_notas_credito_numero'), table_name='notas_credito')
    op.drop_table('notas_credito')
    # ### end Alembic commands ###
